USE tienda;

/* 1 */ SELECT nombre FROM producto;
/* 2 */ SELECT nombre, precio FROM producto;
/* 3 */ SELECT * FROM producto;
/* 4 */ SELECT nombre , precio , precio * 1,09 FROM producto;
/* 5 */ SELECT nombre, precio AS precio_euros, precio * 1,09 AS precio_dolares FROM producto;
/* 6 */ SELECT UPPER(nombre), precio FROM producto; 
/* 7 */ SELECT LOWER(nombre), precio FROM producto;
/* 8 */ SELECT nombre, UPPER(SUBSTRING(nombre, 1,2)) FROM fabricante;
/* 9 */ SELECT nombre, ROUND(precio) FROM producto;
/* 10 */ SELECT nombre, TRUNCATE(precio, 0) FROM producto;
/* 11 */ SELECT codigo_fabricante FROM producto;
/* 12 */ SELECT DISTINCT codigo_fabricante FROM producto;
/* 13 */ SELECT nombre FROM fabricante ORDER BY nombre ASC;
/* 14 */ SELECT nombre FROM fabricante ORDER BY nombre DESC;
/* 15 */ SELECT nombre FROM fabricante ORDER BY nombre ASC price DESC;
/* 16 */ SELECT * FROM fabricante LIMIT 5;
/* 17 */ SELECT * FROM fabricante LIMIT 2 OFFSET 3;
/* 18 */ SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
/* 19 */ SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
/* 20 */ SELECT nombre FROM producto WHERE codigo_fabricante = 2;
/* 21 */ SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f;
/* 22 */ SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ORDER BY f.nombre;
/* 23 */ SELECT p.codigo, p.nombre, f.codigo, f.nombre FROM producto p JOIN fabricante;
/* 24 */ SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ORDER BY p.precio ASC LIMIT 1;
/* 25 */ SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ORDER BY p.precio DESC LIMIT 1;
/* 26 */ SELECT p.* FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo';
/* 27 */ SELECT p.* FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Crucial' AND p.precio > 200;
/* 28 */ SELECT p.* FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre ='Seagate';
/* 29 */ SELECT p.* FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre IN ('Asus','Hewlett-Packard', 'Seagate');
/* 30 */ SELECT p.* FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%e';
/* 31 */ SELECT p.* FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%w%';
/* 32 */ SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante ON p.codigo_fabricante = f.codigo f WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC;
/* 33 */ SELECT DISTINCT p.codigo_fabricante, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
/* 34 */ SELECT f.*, p.* FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante;
/* 35 */ SELECT f.* FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante WHERE p.codigo_fabricante IS NULL;
/* 36 */ SELECT * FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo');
/* 37 */ SELECT p.* FROM producto p WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo') AND precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'));
/* 38 */ SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo' AND p.precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo')); 
/* 39 */ SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Hewlett-Packard' AND p.precio = (SELECT MIN(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Hewlett-Packard'));
/* 40 */ SELECT p.* FROM producto p WHERE precio >= (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'));
/* 41 */
